import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import DD from "../assets/svg/dd_logo_website.svg";
import { Kanit } from "next/font/google";
import Link from "next/link";
import localFont from "next/font/local";
import Subnavigation from "@/components/navigation/subnavigation";
import Footer from "@/components/footer/footer";
import Navigation from "@/components/navigation/navigation";
import BurgerNavigation from "@/components/navigation/burger-navigation";

const pp = localFont({
  src: [
    {
      path: "../fonts/PPTelegraf-Ultrabold.otf",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={pp.className}>
      <body className="overflow-x-hidden w-full ">
        <div className="flex justify-start w-screen ml-11 xl:ml-0 lg:justify-center xl:mt-2">
          <Link className="absolute my-11" href="../">
            <Image src={DD} alt="DD logo" />
          </Link>
        </div>
        <div className="">
          <div className="fixed left-10 top-[50%] -translate-y-[50%] z-50">
            <Navigation />
          </div>
          <div className="absolute right-[10%] mt-20">
            <BurgerNavigation />
          </div>
          <main className="">{children}</main>
          <aside className="fixed right-10 top-[50%] -translate-y-[50%] z-50">
            <Subnavigation />
          </aside>
        </div>
        <Footer />
      </body>
    </html>
  );
}
